drop empty arrays
SamVerschueren/obj-clean pull request #2
Opened 2017-02-09 19:32 UTC by kasperlewau

Had a use case that obj-clean appeared to take care of brilliantly up until the point where I hit empty arrays. I figured I'd submit a PR and see if I can get away with not having to maintain a fork : ]

Updated the ava assertions & added a space to satisfy the latest xo/ava rules.

2017-02-09 19:36 UTC, SamVerschueren commented
Seems like a legitimate use case. Just wondering if I should make it optional with a flag or something. Have to come up with the use cases where I'm using it for to make sure it's desired behaviour.

2017-02-09 19:36 UTC, SamVerschueren commented
Set the `xo` version to `0.16.0`. It dropped support for older Node versions.

2017-02-09 19:42 UTC, kasperlewau commented
Have to pin the `ava` version as well. It is failing at 0.12.0.

2017-02-22 16:54 UTC, SamVerschueren commented
Could you make this optional? Add a `preserveArrays` option that is `true` by default.

2017-02-22 16:55 UTC, kasperlewau commented
Can do!

2017-02-22 16:56 UTC, kasperlewau commented
Would you prefer for that to be `clean({}, true|false)` or `clean({}, { preserveArray: false })`?

2017-02-22 17:00 UTC, SamVerschueren commented
The options object `clean({}, { preserveArray: false })`

2017-02-22 17:02 UTC, kasperlewau commented
👍

2017-02-23 06:38 UTC, SamVerschueren requested changes
Some small improvements :). Thanks for working on this!

2017-02-23 06:38 UTC, SamVerschueren commented on readme.md
> +Type: `boolean`
Add `<br>` at the end of this line

2017-02-23 06:38 UTC, SamVerschueren commented on readme.md
> +clean({foo: 'bar', baz: []}, {preserveArrays: false})
Add an extra example above this one

```js
clean({foo: 'bar', baz: []});
//=> {foo: 'bar', baz: []}
```

2017-02-23 06:38 UTC, SamVerschueren commented on index.js
> +	options = options || {preserveArrays: true};
```js
options = Object.assign({
    preserveArrays: true
}, options);
```

2017-02-23 07:48 UTC, kasperlewau commented
Looks like we broke `0.12` & `0.10` with `Object.assign`.

Not sure why the addition of the `br` in readme didn't get picked up by GitHub as changed. /shrug

2017-02-23 08:50 UTC, SamVerschueren commented
Oh you're right. Use [object-assign](https://github.com/sindresorhus/object-assign) for now. And let's ES2015ify after this PR gets merged.

2017-02-23 10:09 UTC, kasperlewau commented
I'm cool with that - given that we do an ES2015ification _after_ the merge of this PR and do a major version bump. 

That way I can target the version prior to the major and not suffer from an increased transpilation footprint or having to maintain an `--ignore /node_modules\/(?!dot-prop|obj-clean)/` regex.

Those are only ever issues if the consumer is targeting a browser though. 

I'll push the addition of `object-assign` when I'm off from work :)

2017-02-23 11:01 UTC, SamVerschueren commented
Yes, will release first and do major bump after ES2015ify.

2017-02-23 15:14 UTC, merged

2017-02-23 15:27 UTC, SamVerschueren commented
Awesome! Thanks for  working on this! Releases as `1.1.0`.

2017-02-23 15:32 UTC, kasperlewau commented
Thank you!